version: '3'

networks:
  db-tier:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
    networks:
      - db-tier
    volumes:
      - ${REDIS_VOLUME_PATH}:/bitnami/redis/data
    ports:
      - "127.0.0.1:6379:6379"
  pexels-api:   
    depends_on:
      - redis 
    image: 'fiendofsound/pexels-api:main'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=${REDIS_PASSWORD}
      - API_PRODUCER=true
      - PORT=5256
    ports:
      - "5256:5256"
    networks:
      - db-tier
  pexels-queue-consumer:   
    depends_on:
      - redis
      - pexels-api
    image: 'fiendofsound/pexels-api:main'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=${REDIS_PASSWORD}
      - PEXELS_API_KEY=${PEXELS_API_KEY}
      - QUEUE_CONSUMER=true
      - REQUESTS_PER_SECOND=1
    networks:
      - db-tier
  pexels-ui: 
    depends_on:
      - pexels-api
    image: 'fiendofsound/pexels-ui:main'
    environment:
      - SSR_API_URL=http://pexels-api:5256/
      - PUBLIC_API_URL=http://localhost:5256/
      - PORT=5257
    ports:
      - "5257:5257"
